import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavMenu from './NavMenu';
import AuthProvider from './AuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Next.js + TypeScript Starter',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<AuthProvider>
			<html lang='en'>
				<body>
					<div >
						<NavMenu />
						{children}
					</div>
				</body>
			</html>
		</AuthProvider>
	);
}
